import React, { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Paper from '@mui/material/Paper'
import Container from '@mui/material/Container'
import Stack from '@mui/material/Stack'
import { Todo } from './api/todos'
import AddTodo from '../components/AddTodo'
import TodoList from '../components/TodoList'

const Home: NextPage = () => {
  const [todos, setTodos] = useState<Todo[]>([])

  useEffect(() => {
    fetch('/api/todos')
      .then(res => res.json())
      .then(data => {
        setTodos(data.todos)
      })
  }, [])

  useEffect(() => {
    console.log(JSON.stringify(todos, null, 2))
  }, [todos])

  const onAddTodo = (todo: Todo) => {
    setTodos([...todos, todo])
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Paper
            elevation={3}
            sx={{
              margin: 1,
              padding: 1,
            }}>
            <Stack>
              <AddTodo todos={todos} onAddTodo={onAddTodo} />
              <TodoList todos={todos} setTodos={setTodos} />
            </Stack>
          </Paper>
        </Container>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
